name: DCakeLibrary
version: '${project.version}'
main: pl.crazydev.dcakelibrary.DCakeLibrary
api-version: 1.19
commands:
  customitems:
    description: custom items
  test:
    description: test command
permissions:
  d-cake-library.custom-items:
    description: gets all custom items
